Exception in thread NeptuneAsyncOpProcessor:
Traceback (most recent call last):
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/neptune/internal/operation_processors/async_operation_processor.py", line 297, in run
    super().run()
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/neptune/internal/threading/daemon.py", line 96, in run
    self.work()
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/neptune/internal/operation_processors/async_operation_processor.py", line 315, in work
    self.process_batch([element.obj for element in batch], batch[-1].ver, batch[-1].at)
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/neptune/internal/threading/daemon.py", line 121, in wrapper
    result = func(self_, *args, **kwargs)
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/neptune/internal/operation_processors/async_operation_processor.py", line 339, in process_batch
    processed_count, errors = self._processor._backend.execute_operations(
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/neptune/internal/backends/hosted_neptune_backend.py", line 511, in execute_operations
    self._execute_operations(
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/neptune/common/backends/utils.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/neptune/internal/backends/hosted_neptune_backend.py", line 675, in _execute_operations
    result = self.leaderboard_client.api.executeOperations(**kwargs).response().result
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/neptune/internal/backends/swagger_client_wrapper.py", line 110, in __call__
    future = self._api_method(*args, **kwargs)
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/bravado/client.py", line 271, in __call__
    request_params = construct_request(
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/bravado/client.py", line 312, in construct_request
    construct_params(operation, request, op_kwargs)
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/bravado/client.py", line 335, in construct_params
    marshal_param(param, param_value, request)
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/bravado_core/param.py", line 155, in marshal_param
    request['data'] = json.dumps(value)
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/simplejson/__init__.py", line 378, in dumps
    return _default_encoder.encode(obj)
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/simplejson/encoder.py", line 298, in encode
    chunks = self.iterencode(o)
  File "/home/rosengaard/miniforge3/envs/and3.9/lib/python3.9/site-packages/simplejson/encoder.py", line 379, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
[neptune] [warning] /home/rosengaard/mri-infarct-segmentation/Anders/V3/Unet_C3/JAG/Slurm/trainUnet_C3.py:303: NeptuneUnsupportedValue: WARNING: A value you're trying to log (`nan`) will be skipped because it's a non-standard float value that is not currently supported.
